### PR TITLE
Handle zero-width intervals correctly

### LINKED ISSUE #101: [TI-97] timew assertion error on delete
_Thomas Lauf on 2018-01-03T06:07:49Z says:_ 

 Originally reported by [~chaseadam]

I am trying to correct a task which I left running by deleting it, but I am getting an assertion error:
```
timew delete @1

timew: /home/achasen/git/timew-1.0.0/src/Datafile.cpp:111: void Datafile::deleteInterval(const Interval&): Assertion `_range.overlap (interval.range)' failed.

[1]    14876 abort (core dumped)  timew delete @1
```
the output of summary is:
```
W52 2017-12-30 Sat @3 sfdc, slides       10:45:00 11:39:01  0:54:01
                   @2 calendar, review   11:39:21 11:45:35  0:06:14
                   @1 review, tech, test 11:45:35  0:00:00 12:14:25 13:14:40
W52 2017-12-31 Sun @1 review, tech, test  0:00:00  0:00:00 24:00:00 24:00:00
```

### LINKED ISSUE #164: [Question] Overlapping zero-width intervals
While working on a fix for #101 and a related issue I noticed that a zero-width interval `Z = [p, p)` is **not** considered to overlap an interval `[p, q)`, where `q ≥ p`.

Currently, the following intervals overlap, as they should:

```text
a  p  q
[-----)
   Z
```

However, these two intervals do not overlap, even though the first interval is half-closed.

```text
p     q
[-----)
Z
```

This behavior is easy to change and would allow for zero-width intervals to be stored at the beginning of a datafile segment. Currently, attempting to add a zero-width interval to the beginning of a segment results in an assertion failure because there is no overlap and therefore nothing to store in the datafile. (#101)

```text
    Jan        Feb
[---------)[---------)
           Z

=> overlap(Feb, Z) = false
=> Feb ∩ Z = [NULL, NULL)
```

However, this change would make it impossible for users to store multiple intervals with the same start time. For example:

```text
[---)                 # Unrelated interval A
               [---)  # Unrelated interval B
        Z             # Zero-width interval at point p
[------------------)  # Interval computed by Timewarrior for overlap checking
        [---)         # Interval the user attempts to add
```

In this case, the zero-width interval overlaps the computed interval, so it is used for overlap checking. The zero-width interval would then (with this change) overlap the new interval the user wanted to add, because both intervals cover point `p`, and Timewarrior would cancel the transaction.

Two tests currently rely on being able to start an interval `[p, ∞)` when there already is a zero-width interval `Z = [p, p)` in the database:

* [`TestClock.test_start_additional`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/test/clock.t#L96)
* [`TestClock.test_start_subtract`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/test/clock.t#L120)

Worse, this change would cause problems with existing databases. For this reason it is necessary to leave the overlap checking in [`validate.cpp`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/src/validate.cpp#L106) unchanged.

Proposed solutions, in order of preference:

* Create a `lenientOverlap()` method with the current behavior for use during overlap checking, and change the current [`overlap()`](https://github.com/GothenburgBitFactory/timewarrior/blob/1.1.1/src/Range.cpp#L133) method to use the more consistent and logically correct behavior. This is the best solution in my opinion.
* Do the opposite, creating a `strictOverlap()` method instead.
* Make the `overlap()` method asymmetric, so that `A` may overlap `Z` without `Z` overlapping `A`. I find this solution counter-intuitive and would not recommend it.

Any thoughts? @lauft

### LINKED ISSUE #165: CmdSummary does not show empty intervals at midnight
```text
$ timew track 2018-08-10 - 2018-08-10
  Recorded 
    Started 2018-08-10T00:00:00
    Ended                    00
    Total               0:00:00

$ timew summary :year :ids
  (shows an empty list)
```

### PR DESCRIPTION
**Pull request by janikrabe**
This pull request introduces two additional methods, `segmentContains` and `intersects`, that are needed to correctly handle empty intervals.

Fixes #101
Fixes #165
Closes #164

### CODE REVIEW

File: src/Range.cpp [hunk 1]
```diff
@@ -179,6 +179,43 @@ bool Range::encloses (const Range& other) const
...
+//   B                          [...
+//
+// this                     [...
+//   A                        [----)
+//   B                           [--------)
+//   C                                    [--------)
+//   D                         [...
+//   E                                 [...
+//
+bool Range::segmentContains (const Range& other) const
```
Comment (janikrabe) [inline src/Range.cpp]: Like `encloses` in that an interval `A` may enclose a zero-width interval `Z` even though `A` and `Z` do not overlap, but unlike `encloses` this method does not require the enclosed interval to have an end time.

File: src/Range.cpp [hunk 2]
```diff
@@ -229,9 +266,26 @@ Range Range::intersect (const Range& other) const
     return result;
   }
 
+  // If there is an intersection but no overlap, we have a zero-width
+  // interval [p, p) and another interval [p, q), where q >= p.
+  if (intersects (other))
```
Comment (janikrabe) [inline src/Range.cpp]: We define `p ∈ [p, p)`, so if `q ≥ p` then `[p, p) ∩ [p, q) = {p}`.

File: src/Range.cpp [hunk 3]
```diff
@@ -229,9 +266,26 @@ Range Range::intersect (const Range& other) const
...
+    return Range {start, start};
+
   return Range {};
 }
 
+////////////////////////////////////////////////////////////////////////////////
+bool Range::intersects (const Range &other) const
```
Comment (janikrabe) [inline src/Range.cpp]: Checks whether `A ∩ B ≠ ∅`. Similar to `overlap` but allows for intersections of the form `[p, p) ∩ [p, q)`.

**Comment by janikrabe** [comment]
Added tests for #101 and #165.

File: src/Range.cpp [hunk 4]
```diff
@@ -179,6 +179,43 @@ bool Range::encloses (const Range& other) const
...
+//   E                                 [...
+//
+bool Range::segmentContains (const Range& other) const
+{
+  if (is_started ())
+  {
+    if (is_ended ())
+    {
+      if (other.is_started () && other.start >= start)
+        return ! other.is_ended () || other.end <= end;
```
Comment (lauft) [inline src/Range.cpp]: At this position (line 207) we know `this` is a closed interval and the start date of `other` is within this interval. If `other` is a closed interval, `segmentContains` returns true if the end date of `other` is within `this`. If `other` is open `segmentContains` always returns true.

Why this difference between
```
this  [...]
other   [.....
```
and
```
this  [...]
other   [.....]
```
?

Comment (janikrabe) [reply src/Range.cpp]: `segmentContains` is used to check whether a `Range` can be stored in a `Datafile`. The range to be stored must be enclosed in the range covered by the datafile because a single range cannot extend beyond the end of a data file (e.g., `2018-01-15 - 2018-02-15` is actually stored as `2018-01-15 - 2018-01-31` in `2018-01.data` and as `2018-02-01 - 2018-02-15` in `2018-02.data`).

However, when a range doesn't have an end date, it would have to be stored in an infinite number of data files. To work around that, we instead store it in the file containing its start date. This is consistent with the current behavior.

Here, `other` is stored in the data file with range `this`:

```text
this  [...]
other   [.....
```

However, in the following case, `other` extends beyond the end of `this` and would cause an assertion failure when stored in the data file with range `this`:

```text
this  [...]
other   [.....]
```
